apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: ghcr.io/reshmasj/task:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

