name: Build and Store Node.js App Artifact 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Archive production files
        run: |
          mkdir artifact
          cp -r index.js package*.json node_modules artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-app-artifact
          path: artifact/
