name: Promote to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev, qa, uat, prod)"
        required: true
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod
    
jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      # Requires protection rule for manual approval (set in GitHub UI)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Login to Azure AKS
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group myResourceGroup --name myAKSCluster --overwrite-existing

      - name: Set environment namespace
        run: echo "ENV_NAMESPACE=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
        

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8/deployment.yaml --namespace=$ENV_NAMESPACE
          
          kubectl set image deployment/nodejs-app nodejs-app=ghcr.io/reshmasj/task:${{ env.IMAGE_TAG }} -n ${ENV_NAMESPACE}
          kubectl apply -f k8/service.yaml -n ${ENV_NAMESPACE}
          kubectl rollout status deployment/nodejs-app -n ${ENV_NAMESPACE}
         
          
